import type { Metadata } from 'next'
import Sidebar from '@/components/Sidebar'

import { Inter } from 'next/font/google'
import './globals.css'
import SupabaseProvider from '@/providers/SupabaseProvider'
import UserProvider from '@/providers/UserProvider'
import ModalProvider from '@/providers/ModalProvider'
import ToasterProvider from '@/providers/ToasterProvider'
import getShabadsByUserId from '@/actions/getShabadsByUserId'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sikhi - Web Player: Music for Sikhs',
  description: 'Generated by create next app',
}

export const revalidate = 0;
 
export default async function RootLayout({children,}: {children: React.ReactNode}) {
  const userShabads = await getShabadsByUserId();
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider />
        <SupabaseProvider>
          <UserProvider>
            <ModalProvider />
              <Sidebar shabads={userShabads}>
                {children}
              </Sidebar>
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
}
